drone:  
  model_name: "hummingbird"

  # ==================== whole-body parameters ====================
  marker:
    enable: true            # whether to attach a marker at drone center
    shape: "drone_base"     # obj file name. cuboid_1 drone_base
  # ==================== whole-body ====================

sensor:
  lidar_range: 4.
  lidar_vfov: [-80., 80.] # degrees
  lidar_vbeams: 17 # number of  vertical beams
  lidar_hres: 10. # degree
  