defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False
device: "cuda:0"
seed: 6

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
env:
  num_envs: 2 # Number of drones for training
  max_episode_length: 2200
  env_spacing: 8.0 
  num_obstacles: 200

  # ==================== whole-body reward ====================
  height_penalty_weight: 8.0     # Weight for the height penalty term
  min_flight_height: 0.5         # Minimum allowed flight height (m)
  max_flight_height: 3.5         # Maximum allowed flight height (m)
  safety_reward_k: 0.4           # Decay rate: larger k = faster saturation
  smoothness_weight: 0.1         # Weight for the smoothness penalty term
  reward_bias: -0.1             # Constant reward bias to encourage exploration

  #  whole-body curriculum
  curriculum_total_steps: 1_000_000   
  curriculum_step_divisor: 1.0        
  curriculum_r1_steps: 10000       
  curriculum_r2_steps: 50000    

  vel_weight_start: 1.5
  vel_weight_end: 1.5
  safety_weight_start: 1.0
  safety_weight_end: 1.0
  safety_dyn_weight_start: 1.0  
  safety_dyn_weight_end: 1.0
  curriculum_log_interval: 1000
  curriculum_freeze_in_eval: true

  # ==================== whole-body reward ====================


  # ==================== whole-body map ====================
  # Switch Maps (sphere, vanilla, oblique, hole)
  map_name: "vanilla"
  
  # Static horizontal beams configuration
  num_static_beams: 60              # Number of horizontal beams
  beam_length_range: [1.0, 8.0]    # Beam length range (m)
  beam_thickness_range: [0.3, 0.8]  # Beam thickness range (m)
  beam_height_range: [0.3, 5.0]     # Beam height above ground (m)

  # Sphere Map Obstacles
  percent_cubes: 0.2
  percent_cylinders: 0.4
  percent_spheres: 0.4
  cube_size_range: [0.5, 2.0]
  cylinder_height_range: [1.0, 6.0]
  cylinder_radius_range: [0.2, 0.8]
  sphere_radius_range: [0.5, 1.5]
  clearance_range: [0.1, 1.5]

  # Oblique Map Obstacles Num (Percentage)
  percent_oblique: 0.5
  col_length_range: [2.0, 6.0]
  col_thickness_range: [0.2, 0.4]
  col_base_z_range: [0.0, 0.5]
  col_pitch_range: [0.0, 0.785]

  # Hole Map Obstacles Num (Percentage)
  percent_hole: 0.2
  # Hole Map Obstacles Property
  wall_length_range: [3.0, 8.0]
  wall_thickness_range: [0.1, 0.3]
  wall_height_range: [2.0, 4.0]
  wall_hole_length_range: [0.8, 2.0]
  wall_hole_height_range: [0.8, 1.5]
  wall_hole_bottom_clearance: 0.5
  wall_hole_side_clearance: 0.5
  # ==================== whole-body map ====================

env_dyn:
  num_obstacles: 80
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: wb # whole_body_navrl 
  name: wb # omni-wb
  entity: chai8226-sichuan-university 
  mode: offline # online
  run_id: #kw9xf9k9
