defaults:
  - _self_
  - drone
  - ppo
  - sim

headless: False
device: "cuda:0"
seed: 0

# Total Training Length
max_frame_num: 12e8 # max frame 
eval_interval: 1000 # evaluate the policy for every N training steps
save_interval: 1000

# Training Environment
env:
  num_envs: 2 # Number of drones for training
  max_episode_length: 2200
  env_spacing: 8.0 
  num_obstacles: 200

  # ==================== whole-body ====================
  # Flight height constraints
  min_flight_height: 0.5         # Minimum allowed flight height (m)
  max_flight_height: 3.5         # Maximum allowed flight height (m)
  height_penalty_deadzone: 0.2   # Buffer zone before penalty applies (m)
  height_penalty_weight: 8.0     # Weight of height penalty in reward function
  height_penalty_huber_delta: 0.5 # Huber loss delta: transition point from L2 to L1 (m)
  
  # Static horizontal beams configuration
  num_static_beams: 50             # Number of horizontal beams
  beam_length_range: [1.0, 10.0]    # Beam length range (m)
  beam_thickness_range: [0.5, 1.0]  # Beam thickness range (m)
  beam_height_range: [0.5, 3.5]     # Beam height above ground (m)
  # ==================== whole-body ====================

env_dyn:
  num_obstacles: 80 # set to zero if static env is needed
  vel_range: [0.5, 1.5]
  local_range: [5.0, 5.0, 4.5]

viewer:
  eye: [0., 40., 40.]
  lookat: [0., 2.5, 0.]
  resolution: [960, 720]

wandb:
  project: wb
  name: wb
  entity: chai8226-sichuan-university
  mode: offline # online
  run_id: #kw9xf9k9
